version: '3'
services:
  nuxt:
    container_name: nuxt
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./server:/workspace
      - node_modules_volume:/workspace/node_modules
    working_dir: /workspace
    tty: true

volumes:
  node_modules_volume: